//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mono.Api.AmazonApi.Test.AmazonProxyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Mono.Api.AmazonProxyService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AmazonProxyService.IAmazonService")]
    public interface IAmazonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmazonService/GetData", ReplyAction="http://tempuri.org/IAmazonService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmazonService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAmazonService/GetDataUsingDataContractResponse")]
        Mono.Api.AmazonApi.Test.AmazonProxyService.CompositeType GetDataUsingDataContract(Mono.Api.AmazonApi.Test.AmazonProxyService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmazonService/ItemSearch", ReplyAction="http://tempuri.org/IAmazonService/ItemSearchResponse")]
        string ItemSearch(AmazonApi.CountryType countryType, AmazonApi.SearchIndexType indexType, int itemPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmazonService/AvailableTypes", ReplyAction="http://tempuri.org/IAmazonService/AvailableTypesResponse")]
        AmazonApi.SearchIndexType[] AvailableTypes(AmazonApi.CountryType countryType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmazonServiceChannel : Mono.Api.AmazonApi.Test.AmazonProxyService.IAmazonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmazonServiceClient : System.ServiceModel.ClientBase<Mono.Api.AmazonApi.Test.AmazonProxyService.IAmazonService>, Mono.Api.AmazonApi.Test.AmazonProxyService.IAmazonService {
        
        public AmazonServiceClient() {
        }
        
        public AmazonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmazonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmazonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmazonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public Mono.Api.AmazonApi.Test.AmazonProxyService.CompositeType GetDataUsingDataContract(Mono.Api.AmazonApi.Test.AmazonProxyService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string ItemSearch(AmazonApi.CountryType countryType, AmazonApi.SearchIndexType indexType, int itemPage) {
            return base.Channel.ItemSearch(countryType, indexType, itemPage);
        }
        
        public AmazonApi.SearchIndexType[] AvailableTypes(AmazonApi.CountryType countryType) {
            return base.Channel.AvailableTypes(countryType);
        }
    }
}
